spring.application.name=YoutubeTools
youtube.api.key=AIzaSyA4No_-WMNMcQXG2UVjpT87u7kNzaUx8Dg
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.search.url=${youtube.api.base.url}/search

youtube.api.videos.url=${youtube.api.base.url}/videos

#max number of related videos

youtube.api.max.related.videos=3

